### ISSUE TITLE
Messenger MAI blocks path with own units

### ISSUE THREAD

**Issue by Vultraz** [mattsc/AI-demos#10]
In my scenario, I used the hang out MAI in combination with the messenger MAI. This resulted in a large number of units. At the appropriate time, the hang out MAI gave way to the messenger MAI, but after the first waypoint the messenger (highlighted in black) and the large group of units barely moves at all.

There is at least one hex that the messenger could move to since its own units are blocking the path to the next waypoint, (highlighted in red) but it doesn't.

The next two waypoints are highlighted in blue.

![messengermaiexample](https://f.cloud.github.com/assets/3558659/1009869/ed2bbc82-0b3f-11e3-8021-677b54c3fd33.PNG)

**Comment by mattsc** [comment]
Closing as the messenger MAI is in mainline now.  If this is still an issue, this should be moved there.
