### ISSUE TITLE
LUA Errors at turn 1 of Fred scenario

### ISSUE THREAD

**Issue by cbeck88** [mattsc/AI-demos#11]
Hi, 

I downloaded the add-on and tried to fire up a game with Fred at the latest master version (1.13+dev), unfortunately I got a bunch of Lua errors reported to the screen:

http://imgur.com/bBweNDw

I decided to try checking out an older version of master, so I arbitrarily picked out a commit from December: https://github.com/wesnoth/wesnoth/commit/8a024c06380488eaac63f44ec57f89a20c9c91e8

Unforunately I got apparently the same errors:

http://imgur.com/yaerxDd

~iceiceice~

**Comment by mattsc** [comment]
Closing this as nobody else seems to have encountered this in 3 years.
